name: Simple DLNA
description: "Lightweight DLNA server based on ReadyMedia (minidlna). Streams video from local or USB storage."
version: "0.1.23"
slug: simple-dlna
url: "https://github.com/alekslegkih/hassio-addons"
arch:
  - aarch64
  - amd64
image: "ghcr.io/alekslegkih/simple-dlna-{arch}"
host_network: true
init: true
startup: services
watchdog: http://localhost:8200
panel_icon: mdi:dlna
panel_title: DLNA
options:
  mountpoint: "/media"
  friendly_name: "HAOS-DLNA"
  enable_subtitles: true
schema:
  mountpoint: str
  friendly_name: str
  enable_subtitles: bool
map:
  - addon_config:rw
  - media:rw  
ports:
  8200/tcp: 8200
ports_description:
  8200/tcp: Web interface 
webui: "http://localhost:[PORT:8200]"

