name: Simple DLNA
description: "Lightweight DLNA server based on ReadyMedia (minidlna). Streams video from local or USB storage."
version: "0.2.3"
slug: simple-dlna
url: "https://github.com/alekslegkih/hassio-addons"
arch:
  - aarch64
  - amd64
image: "ghcr.io/alekslegkih/simple-dlna-{arch}"
host_network: true
init: true
ports:
  8200/tcp: 8200
ports_description:
  8200/tcp: Static server
webui: "http://[HOST]:[PORT:8200]"
startup: services
options:
  media_dir: "/media"
  friendly_name: "HAOS-DLNA"
  log_level: "warn"
schema:
  media_dir: str
  friendly_name: str
  log_level: list(off|fatal|error|warn|info|debug) 
map:
  - addon_config:rw
  - media:rw  
panel_icon: mdi:dlna
panel_title: DLNA

