name: Gotify Server
description: Gotify local notification server
version: "0.2.4"
slug: gotify-server
url: "https://github.com/alekslegkih/hassio-addons"
arch:
  - aarch64
  - amd64
image: ghcr.io/alekslegkih/gotify-server-{arch}
host_network: false
startup: application
init: false
map:
  - addon_config:rw
  - ssl
ports:
  80/tcp: 8486
ports_description:
  8486/tcp: Web interface and API
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
webui: "http://[HOST]:[PORT:8486]"