name: Gotify Server
description: Gotify local notification server
version: "0.4.1"
slug: gotify-server
url: "https://github.com/alekslegkih/hassio-addons"
arch:
  - aarch64
  - amd64
image: ghcr.io/alekslegkih/gotify-server
startup: application
init: true
map:
  - addon_config:rw
ports:
  80/tcp: 8486
ports_description:
  80/tcp: Web interface and API
webui: "http://[HOST]:[PORT:8486]"
panel_icon: mdi:bell-ring
panel_title: gotify