name: Gotify Server
description: Gotify local notification server
version: "0.3.2"
slug: gotify-server
url: "https://github.com/alekslegkih/hassio-addons"
arch:
  - aarch64
  - amd64
image: ghcr.io/alekslegkih/gotify-server-{arch}
startup: application
init: false
map:
  - addon_config:rw
ports:
  80/tcp: 8486
ports_description:
  8486/tcp: Web interface and API
webui: "http://[HOST]:[PORT:8486]"